#Jeremy Persing
range: lab5.o get_range_count.o lab5.h
	gcc lab5.o get_range_count.o -o range
lab5.o: lab5.c lab5.h
	gcc -c lab5.c
get_range_count.o: get_range_count.c lab5.h
	gcc -c get_range_count.c

